import { expect, test } from "bun:test";
import { previewText, type PublishPreview } from "./publish.ts";

const PREVIEW: PublishPreview = {
  status: "planned",
  sourceId: "acme/app#9",
  repository: "acme/app",
  publication: 2,
  planRevision: "revision-1",
  ships: {
    remote: { name: "origin", url: "git@github.com:acme/app.git" },
    target: "main",
    base: "base-1",
    head: "head-1",
    parts: [
      {
        name: "operator/acme-app-9/1",
        commit: "commit-1",
        base: "main",
        title: "First part",
        body: "The first body.\n",
        cut: null,
      },
      {
        name: "operator/acme-app-9/2",
        commit: "commit-2",
        base: "operator/acme-app-9/1",
        title: "Second part",
        body: "The second body.\n",
        cut: { after: "commit-1", reason: "The API lands first." },
      },
    ],
    trackerSteps: [
      {
        part: 1,
        commit: "commit-1",
        closes: "acme/app#1",
        resolution: "Resolved by the first part.\n",
        behaviorChanges: [],
      },
      {
        part: 2,
        commit: "commit-2",
        closes: "acme/app#2",
        resolution: "Resolved by the second part.\n",
        behaviorChanges: [],
      },
    ],
  },
  approval: {
    action: "publish",
    targets: ["github:acme/app#2:map_amendment"],
    scope: "acme/app#9",
    requestRevision: "revision-1",
  },
  info: {
    targetTip: "tip-1",
    commitsBehind: 3,
    mergesCleanly: false,
    otherMethodsAllowed: ["squash"],
    unverifiedRules: ["branch rules of main: unread"],
  },
  refusals: [{ reason: "stack_part_open", detail: "Part 1 stays open." }],
  closes: [
    { number: 4, url: null, head: "old-4" },
    { number: 5, url: "https://github.com/acme/app/pull/5", head: "old-5" },
  ],
  headMoved: [{ number: 6, url: "https://github.com/acme/app/pull/6", head: "old-6" }],
  planPath: ".operator/local/publish-plans/revision-1.md",
};

// The person approves the exact text of the plan file, so its bytes are pinned here.
test("the publish plan file holds every section, title, and body verbatim", () => {
  expect(previewText(PREVIEW)).toBe(
    [
      "# Publish plan revision-1",
      "",
      "- Source: acme/app#9",
      "- Stack publication: 2",
      "- Remote: origin (git@github.com:acme/app.git)",
      "- Target branch: main",
      "- Integration base: base-1",
      "- Head: head-1",
      "- New remote branches: operator/acme-app-9/1, operator/acme-app-9/2",
      "- Target tip: tip-1",
      "- Commits on the target since the base: 3",
      "- The head merges cleanly onto the tip: no",
      "- Other merge methods the repository allows: squash",
      "- Unverified: branch rules of main: unread",
      "",
      "## Pull requests this publication closes",
      "",
      "Each one gets one comment that names its replacement, then it is closed with no merge. Its branch stays.",
      "",
      "- #4",
      "- #5 https://github.com/acme/app/pull/5",
      "",
      "## Replaced pull requests that get no write",
      "",
      "A person moved the head of each one, so Operator writes nothing more to it, no comment and no close (decision 21). A person closes it.",
      "",
      "- #6 gets no write: https://github.com/acme/app/pull/6",
      "",
      "## Refusals",
      "",
      "- stack_part_open: Part 1 stays open.",
      "",
      "## Tracker steps after the merge",
      "",
      "Each step runs only after its pull request merged into the target, under this approval.",
      "The completion step closes the ticket as completed, or observes the close that its closing keyword made.",
      "The resolution is this text, with the number GitHub gives the pull request.",
      "After a merge that is not a merge commit, it names the commit that landed and the method instead.",
      "",
      "### github:acme/app#1:resolution and github:acme/app#1:completion",
      "",
      "<!-- resolution start -->",
      "Resolved by the first part.",
      "<!-- resolution end -->",
      "",
      "### github:acme/app#2:resolution and github:acme/app#2:completion",
      "",
      "<!-- resolution start -->",
      "Resolved by the second part.",
      "<!-- resolution end -->",
      "",
      "### github:acme/app#2:map_amendment",
      "",
      "The map amendment of this item runs after the merge, and only after a second approval, `map-amendment`, binds the exact text that the CLI renders then.",
      "",
      "## Pull request 1 of 2: operator/acme-app-9/1 into main",
      "",
      "Title: First part",
      "",
      "The body, exactly as it is created:",
      "",
      "<!-- body start -->",
      "The first body.",
      "<!-- body end -->",
      "",
      "## Pull request 2 of 2: operator/acme-app-9/2 into operator/acme-app-9/1",
      "",
      "Cut after commit-1: The API lands first.",
      "",
      "Title: Second part",
      "",
      "The body, exactly as it is created:",
      "",
      "<!-- body start -->",
      "The second body.",
      "<!-- body end -->",
      "",
    ].join("\n"),
  );
});

test("a refused plan with nothing to ship leaves every empty section out", () => {
  expect(
    previewText({
      ...PREVIEW,
      planRevision: null,
      ships: null,
      approval: null,
      info: null,
      refusals: [],
      closes: [],
      headMoved: [],
    }),
  ).toBe(
    [
      "# Publish plan (refused)",
      "",
      "- Source: acme/app#9",
      "- Stack publication: 2",
      "",
      "## Refusals",
      "",
      "None.",
      "",
    ].join("\n"),
  );
});
