const targetChoice = "(--opencode | --claude | --opencode --claude)";
const selection = "[--operator-host <host>] [--operator-model <model>]";
const crewSelection = "[--crew-host <host>] [--crew-model <model>]";

export const usage = [
  "Usage:",
  "  operator --version [--json]",
  `  operator install ${targetChoice} [--json]`,
  `  operator setup plan ${targetChoice} [--json]`,
  `  operator setup apply ${targetChoice} --approved-plan <planId> [--json]`,
  "  operator setup rollback [--json]",
  `  operator setup readiness ${targetChoice} ${selection} ${crewSelection} [--json]`,
  `  operator setup probe plan ${targetChoice} ${selection} ${crewSelection} [--json]`,
  `  operator setup probe apply ${targetChoice} ${selection} ${crewSelection} --approved-probe <probeId> [--json]`,
  "  operator crew own --request <id> --owner-label <label> [--json]",
  "  operator crew own --request <id> --owner-label <label> --takeover --ownership-revision <n> [--json]",
  "  operator work register --request <id> --owner-token <token> --input <path|-> [--json]",
  "  operator work claim --request <id> --owner-token <token> --assignment <id> --revision <n> [--json]",
  "  operator work accept --request <id> --owner-token <token> --assignment <id> --revision <n> [--attempt <id>] [--submission <id>] [--pr-head <sha>] [--json]",
  "  operator work rework --request <id> --owner-token <token> --assignment <id> --revision <n> --input <path|-> [--json]",
  "  operator work invalidate --request <id> --owner-token <token> --assignment <id> --revision <n> --input <path|-> [--json]",
  "  operator work frontier [--json]",
  `  operator attempt dispatch --request <id> --owner-token <token> --attempt <id> --commit <sha> [--branch <name>] [--worktree <path>] ${crewSelection} [--json]`,
  "  operator attempt acknowledge --request <id> --attempt <id> [--json]",
  "  operator attempt reconcile --request <id> --owner-token <token> --attempt <id> [--json]",
  "  operator attempt replace --request <id> --owner-token <token> --attempt <id> [--inspection <identity>] [--json]",
  "  operator attempt show --attempt <id> [--json]",
  "  operator attempt submit --request <id> --attempt <id> --input <path|-> [--json]",
  "  operator question raise --request <id> --attempt <id> --input <path|-> [--json]",
  "  operator question revise --request <id> --attempt <id> --question <id> --revision <n> --input <path|-> [--json]",
  "  operator question escalate --request <id> --owner-token <token> --question <id> --revision <n> --input <path|-> [--json]",
  "  operator question answer --request <id> --owner-token <token> --question <id> --revision <n> --input <path|-> [--json]",
  "  operator question reapply --request <id> --owner-token <token> --question <id> --revision <n> --answer <id> --approval <id> [--json]",
  "  operator question deliver --request <id> --owner-token <token> --question <id> [--json]",
  "  operator question acknowledge --request <id> --question <id> [--json]",
  "  operator question show --question <id> [--json]",
  "  operator approval grant --request <id> --owner-token <token> --input <path|-> [--json]",
  "  operator approval revoke --request <id> --owner-token <token> --approval <id> --revision <n> [--json]",
  "  operator approval check --input <path|-> [--json]",
  "  operator review report --request <id> --review <id> --input <path|-> [--json]",
  "  operator review dispose --request <id> --owner-token <token> --review <id> --input <path|-> [--json]",
  "  operator review show --review <id> [--json]",
  "",
  "A host is `opencode` or `claude-code`.",
].join("\n");
