import {
  CLAUDE_IMPORT_PATH,
  CONFIG_PATH,
  IGNORE_PATH,
  INSTRUCTIONS_PATH,
  type Observation,
  SCHEMA_PATH,
  type Target,
  toolState,
} from "./observe.ts";

export type Check = {
  name: string;
  target: Target | null;
  kind: "static" | "live";
  state: "passed" | "failed" | "unverified" | "stale";
  reason: string | null;
  detail: string;
  nextAction: string | null;
  conflict: boolean;
  paths: string[];
};

type Failure = {
  reason: string;
  detail: string;
  nextAction: string;
  conflict?: boolean;
  paths?: string[];
};

export function passedCheck(
  name: string,
  target: Target | null,
  detail: string,
  kind: Check["kind"] = "static",
): Check {
  return {
    name,
    target,
    kind,
    state: "passed",
    reason: null,
    detail,
    nextAction: null,
    conflict: false,
    paths: [],
  };
}

export function unmetCheck(
  name: string,
  target: Target | null,
  state: "failed" | "unverified" | "stale",
  failure: Failure,
  kind: Check["kind"] = "static",
): Check {
  return {
    name,
    target,
    kind,
    state,
    reason: failure.reason,
    detail: failure.detail,
    nextAction: failure.nextAction,
    conflict: failure.conflict ?? false,
    paths: failure.paths ?? [],
  };
}

function check(
  name: string,
  target: Target | null,
  passedDetail: string,
  failure: Failure | null,
): Check {
  return failure === null
    ? passedCheck(name, target, passedDetail)
    : unmetCheck(name, target, "failed", failure);
}

function toolCheck(
  observation: Observation,
  name: string,
  tool: "git" | "herdr" | "github",
  purpose: string,
  nextAction: string,
): Check {
  const observed = toolState(observation, tool);
  if (observed?.state === "installed") {
    return check(name, null, `${observed.command} ${observed.version} is installed.`, null);
  }

  return check(name, null, "", {
    reason: "tool_unavailable",
    detail: `${purpose} ${observed?.detail ?? "The tool was not observed."}`,
    nextAction,
  });
}

function gitCheck(observation: Observation): Check {
  const observed = toolState(observation, "git");
  if (observed?.state !== "installed") {
    return check("git", null, "", {
      reason: "tool_unavailable",
      detail: `Operator reads the Git index and needs Git. ${observed?.detail ?? ""}`.trim(),
      nextAction: "Install Git, then check again.",
    });
  }

  const unavailable = observation.plan.conflicts.find((one) => one.reason === "git_unavailable");
  if (unavailable) {
    return check("git", null, "", {
      reason: "git_unavailable",
      detail: unavailable.detail,
      nextAction: "Make the Git index readable in this project, then check again.",
    });
  }

  return check("git", null, `git ${observed.version} is installed.`, null);
}

function bunCheck(observation: Observation): Check {
  const observed = toolState(observation, "bun");
  const version = observed?.version ?? "";
  const supportedBunRange = observation.release.supportedBun;
  if (observed?.state === "installed" && Bun.semver.satisfies(version, supportedBunRange)) {
    return check("bun", null, `Bun ${version} satisfies ${supportedBunRange}.`, null);
  }

  return check("bun", null, "", {
    reason: "tool_unavailable",
    detail: `Operator needs Bun ${supportedBunRange} and observed ${version || "no version"}.`,
    nextAction: `Install Bun ${supportedBunRange}, then check again.`,
  });
}

function lockCheck(observation: Observation): Check {
  const lock = observation.release.lock;
  if (lock.state === "present") {
    return check("lock-data", null, `The installation keeps its ${lock.name} lock data.`, null);
  }

  return check("lock-data", null, "", {
    reason: "lock_data_missing",
    detail: "The Operator installation holds no lock data, so its dependencies are not frozen.",
    nextAction: "Reinstall Operator so the installation keeps its own lock data.",
  });
}

function releaseCheck(observation: Observation): Check {
  const change = observation.plan.changes.find((one) => one.path === SCHEMA_PATH);
  const version = observation.release.version;
  if (change === undefined) {
    return check(
      "operator-release",
      null,
      `${SCHEMA_PATH} matches the schema generated by Operator ${version}.`,
      null,
    );
  }

  if (change.kind === "create") {
    return check("operator-release", null, "", {
      reason: "not_configured",
      detail: `The project holds no ${SCHEMA_PATH}, so it is not configured for Operator ${version}.`,
      nextAction: "Run `operator setup plan`, then apply the approved plan.",
    });
  }

  return check("operator-release", null, "", {
    reason: "release_mismatch",
    detail: `${SCHEMA_PATH} was written by a different Operator release than ${version}.`,
    nextAction: "Run `operator setup plan`, then apply the approved plan.",
    paths: [SCHEMA_PATH],
  });
}

/**
 * The selected release must be the one installed and running.
 * A project that selected none cannot prove this, so the check is unverified rather than failed;
 * every other answer is a blocker, because Operator never substitutes another installation.
 */
function installationCheck(observation: Observation): Check {
  const installation = observation.installation;
  if (installation.status === "installed") {
    return check("operator-installation", null, installation.detail, null);
  }

  const failure = {
    reason: installation.reason,
    detail: installation.detail,
    nextAction: installation.nextAction,
    conflict: installation.reason === "unreadable_selection",
    paths: installation.paths,
  };

  return installation.reason === "release_unselected"
    ? unmetCheck("operator-installation", null, "unverified", failure)
    : unmetCheck("operator-installation", null, "failed", failure);
}

function configurationCheck(observation: Observation): Check {
  const invalid = observation.plan.conflicts.find((one) => one.reason === "invalid_configuration");
  if (invalid) {
    return check("configuration", null, "", {
      reason: "invalid_configuration",
      detail: invalid.detail,
      nextAction: `Correct ${CONFIG_PATH} yourself, then check again.`,
      conflict: true,
      paths: [CONFIG_PATH],
    });
  }

  if (observation.plan.changes.some((one) => one.path === CONFIG_PATH)) {
    return check("configuration", null, "", {
      reason: "not_configured",
      detail: `The project holds no ${CONFIG_PATH}.`,
      nextAction: "Run `operator setup plan`, then apply the approved plan.",
    });
  }

  return check("configuration", null, `${CONFIG_PATH} is present and valid.`, null);
}

function settingsCheck(observation: Observation): Check {
  const tracked = observation.plan.conflicts.find(
    (one) => one.reason === "operator_directory_tracked",
  );
  if (tracked) {
    return check("settings", null, "", {
      reason: "operator_directory_tracked",
      detail: tracked.detail,
      nextAction: "Remove these paths from the Git index yourself, then check again.",
      conflict: true,
      paths: tracked.paths ?? [],
    });
  }

  if (observation.plan.changes.some((one) => one.path === IGNORE_PATH)) {
    return check("settings", null, "", {
      reason: "settings_incomplete",
      detail: `${IGNORE_PATH} does not ignore the local Operator directory.`,
      nextAction: "Run `operator setup plan`, then apply the approved plan.",
    });
  }

  return check("settings", null, "The local Operator directory is ignored and untracked.", null);
}

function selectionCheck(observation: Observation, role: "operator" | "crew"): Check {
  const host = observation.selection[role].host;
  const model = observation.selection[role].model;
  const name = `${role}-selection`;
  const chosenModel =
    model.value === null
      ? `the ${model.source} model`
      : `model ${model.value} from ${model.source}`;

  if (host.value === null) {
    return unmetCheck(name, null, "unverified", {
      reason: "host_unnamed",
      detail: `No session override and no project configuration names the ${role} host, so this selection cannot be checked.`,
      nextAction: `Pass --${role}-host, or set ${role}.host in ${CONFIG_PATH}.`,
    });
  }

  const observed = toolState(observation, host.value);
  if (observed?.state === "installed") {
    // A model name is only checked live, so this check never claims the provider accepts it.
    return check(
      name,
      null,
      `The ${role} runs on ${host.value} from ${host.source}, with ${chosenModel}.`,
      null,
    );
  }

  return check(name, null, "", {
    reason: "host_unavailable",
    detail:
      `The ${host.source} selects ${host.value} for the ${role}, and it is not available. ${observed?.detail ?? ""}`.trim(),
    nextAction: `Install ${host.value}, or select an available host. Operator never substitutes another host.`,
  });
}

function skillCheck(observation: Observation, target: Target): Check {
  const conflicts = observation.skills.conflicts.filter((one) => one.target === target);
  if (conflicts.length > 0) {
    return check("skill-contents", target, "", {
      reason: "skill_copy_modified",
      detail: `The ${target} copy of ${conflicts.map((one) => one.skill).join(", ")} differs from Operator ${observation.release.version}.`,
      nextAction: "Restore or remove each changed copy, then check again.",
      conflict: true,
      paths: conflicts.flatMap((one) => one.paths),
    });
  }

  const missing = observation.skills.missing.filter((one) => one.target === target);
  if (missing.length > 0) {
    return check("skill-contents", target, "", {
      reason: "skills_missing",
      detail: `The ${target} target holds no copy of ${missing.map((one) => one.skill).join(", ")}.`,
      nextAction: `Run \`operator install\` for the ${target} target.`,
      paths: missing.map((one) => one.path),
    });
  }

  return check(
    "skill-contents",
    target,
    `Every discoverable ${target} skill copy matches Operator ${observation.release.version}.`,
    null,
  );
}

function instructionCheck(observation: Observation, target: Target): Check {
  const modified = observation.plan.conflicts.find((one) => one.reason === "instructions_modified");
  if (modified) {
    return check("instruction-loading", target, "", {
      reason: "instructions_modified",
      detail: modified.detail,
      nextAction: `Decide what the marked Operator section in ${INSTRUCTIONS_PATH} should say, then check again.`,
      conflict: true,
      paths: [INSTRUCTIONS_PATH],
    });
  }

  const required =
    target === "claude-code" ? [INSTRUCTIONS_PATH, CLAUDE_IMPORT_PATH] : [INSTRUCTIONS_PATH];
  const missing = required.filter((path) =>
    observation.plan.changes.some((change) => change.path === path),
  );

  if (missing.length > 0) {
    return check("instruction-loading", target, "", {
      reason: "instructions_missing",
      detail: `${target} does not load the Operator instructions from ${missing.join(" and ")}.`,
      nextAction: "Run `operator setup plan`, then apply the approved plan.",
      paths: missing,
    });
  }

  return check(
    "instruction-loading",
    target,
    `${target} loads the Operator instructions from ${required.join(" and ")}.`,
    null,
  );
}

/** Derives every check that observes the current machine and project without launching an agent. */
export function staticChecks(observation: Observation): Check[] {
  return [
    bunCheck(observation),
    gitCheck(observation),
    toolCheck(
      observation,
      "herdr",
      "herdr",
      "Operator launches every Operative through Herdr.",
      "Install Herdr, then check again.",
    ),
    toolCheck(
      observation,
      "github-integration",
      "github",
      "Operator reads and updates the issue tracker through the GitHub CLI.",
      "Install the GitHub CLI, then check again. Static checks do not prove it is authenticated.",
    ),
    lockCheck(observation),
    releaseCheck(observation),
    installationCheck(observation),
    configurationCheck(observation),
    settingsCheck(observation),
    selectionCheck(observation, "operator"),
    selectionCheck(observation, "crew"),
    ...observation.targets.flatMap((target) => [
      skillCheck(observation, target),
      instructionCheck(observation, target),
    ]),
  ];
}
